export const mockInternships = [
  {
    id: 1,
    student_id: "DMCE123",
    student_name: "Isha Jogmarge",
    student_email: "isha.jogmarge@dmce.ac.in",
    company_name: "Google India",
    location: "Mumbai",
    role: "Software Engineering Intern",
    work_mode: "hybrid",
    has_incentives: 1,
    incentive_amount: "50000",
    start_date: "2026-06-01",
    duration: "6 months",
    has_offer_letter: 1,
    offer_letter_key: "mock-key",
    is_completed: 0,
    completion_certificate_key: null,
    status: "pending",
    created_at: "2026-10-08T10:00:00Z",
  },
  {
    id: 2,
    student_id: "DMCE456",
    student_name: "Rahul Patil",
    student_email: "rahul.patil@dmce.ac.in",
    company_name: "Microsoft",
    location: "Remote",
    role: "Cloud Intern",
    work_mode: "remote",
    has_incentives: 1,
    incentive_amount: "45000",
    start_date: "2026-05-15",
    duration: "2 months",
    has_offer_letter: 1,
    offer_letter_key: "mock-key",
    is_completed: 1,
    completion_certificate_key: "mock-key-cert",
    status: "verified",
    created_at: "2026-09-01T10:00:00Z",
  },
  {
    id: 3,
    student_id: "DMCE789",
    student_name: "Sneha Joshi",
    student_email: "sneha.joshi@dmce.ac.in",
    company_name: "ABC Technologies",
    location: "Pune",
    role: "Frontend Intern",
    work_mode: "on-site",
    has_incentives: 0,
    incentive_amount: null,
    start_date: "2026-07-01",
    duration: "3 months",
    has_offer_letter: 1,
    offer_letter_key: "mock-key",
    is_completed: 1,
    completion_certificate_key: "mock-key-cert",
    status: "rejected",
    rejection_reason: "Offer letter document is blurred and unreadable. Please upload a clear PDF.",
    created_at: "2026-09-15T10:00:00Z",
  },
  {
    id: 4,
    student_id: "DMCE234",
    student_name: "Aditya Sharma",
    student_email: "aditya.sharma@dmce.ac.in",
    company_name: "Amazon",
    location: "Bangalore",
    role: "SDE Intern",
    work_mode: "hybrid",
    has_incentives: 1,
    incentive_amount: "80000",
    start_date: "2026-06-10",
    duration: "6 months",
    has_offer_letter: 1,
    offer_letter_key: "mock-key",
    is_completed: 0,
    completion_certificate_key: null,
    status: "pending",
    created_at: "2026-10-05T10:00:00Z",
  },
  {
    id: 5,
    student_id: "DMCE567",
    student_name: "Pooja Desai",
    student_email: "pooja.desai@dmce.ac.in",
    company_name: "TCS",
    location: "Mumbai",
    role: "Systems Intern",
    work_mode: "on-site",
    has_incentives: 1,
    incentive_amount: "25000",
    start_date: "2026-05-01",
    duration: "3 months",
    has_offer_letter: 1,
    offer_letter_key: "mock-key",
    is_completed: 1,
    completion_certificate_key: null, // intentionally missing to show upload pending
    status: "pending",
    created_at: "2026-08-01T10:00:00Z",
  },
];
