const sampleData = {
  students: [
    // ---------- 2020 Batch ----------
    {
      stdID: "2019FHIT001",
      name: "Rohan Das",
      passoutYear: "2020",
      contact: "9811122233",
      mailID: "rohan.das@example.com",
      gender: "Male",
      grade10: 81,
      grade12: 78,
      cgpa: 7.3,
      placedStatus: "Selected",
      placementType: "On Campus",
      companyName: "Infosys",
      roleOffered: "System Engineer",
      salary: 5,
      companiesPlaced: 1,
    },
    {
      stdID: "2019FHIT002",
      name: "Kavita Sinha",
      passoutYear: "2020",
      contact: "9822233344",
      mailID: "kavita.sinha@example.com",
      gender: "Female",
      grade10: 88,
      grade12: 86,
      cgpa: 8.1,
      placedStatus: "Selected",
      placementType: "Off Campus",
      companyName: "TCS",
      roleOffered: "Software Engineer",
      salary: 6,
      companiesPlaced: 1,
    },
    {
      stdID: "2019FHIT003",
      name: "Arvind Rao",
      passoutYear: "2020",
      contact: "9833344455",
      mailID: "arvind.rao@example.com",
      gender: "Male",
      grade10: 77,
      grade12: 74,
      cgpa: 6.9,
      placedStatus: "Rejected",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2019FHIT004",
      name: "Sangeeta Bhatt",
      passoutYear: "2020",
      contact: "9844455566",
      mailID: "sangeeta.bhatt@example.com",
      gender: "Female",
      grade10: 90,
      grade12: 85,
      cgpa: 8.4,
      placedStatus: "Applied",
      placementType: "On Campus",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2019FHIT005",
      name: "Manish Jain",
      passoutYear: "2020",
      contact: "9855566677",
      mailID: "manish.jain@example.com",
      gender: "Male",
      grade10: 79,
      grade12: 75,
      cgpa: 7.0,
      placedStatus: "Unregistered",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },

    // ---------- 2021 Batch ----------
    {
      stdID: "2020FHIT001",
      name: "Ritika Verma",
      passoutYear: "2021",
      contact: "9866677788",
      mailID: "ritika.verma@example.com",
      gender: "Female",
      grade10: 92,
      grade12: 90,
      cgpa: 8.9,
      placedStatus: "Selected",
      placementType: "On Campus",
      companyName: "IBM",
      roleOffered: "Associate Developer",
      salary: 7.5,
      companiesPlaced: 1,
    },
    {
      stdID: "2020FHIT002",
      name: "Sameer Khan",
      passoutYear: "2021",
      contact: "9877788899",
      mailID: "sameer.khan@example.com",
      gender: "Male",
      grade10: 84,
      grade12: 82,
      cgpa: 7.8,
      placedStatus: "Rejected",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2020FHIT003",
      name: "Asha Naik",
      passoutYear: "2021",
      contact: "9888899900",
      mailID: "asha.naik@example.com",
      gender: "Female",
      grade10: 85,
      grade12: 81,
      cgpa: 8.0,
      placedStatus: "Applied",
      placementType: "On Campus",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2020FHIT004",
      name: "Nilesh Tiwari",
      passoutYear: "2021",
      contact: "9899900011",
      mailID: "nilesh.tiwari@example.com",
      gender: "Male",
      grade10: 79,
      grade12: 76,
      cgpa: 7.3,
      placedStatus: "Unregistered",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2020FHIT005",
      name: "Geeta Rawat",
      passoutYear: "2021",
      contact: "9900011223",
      mailID: "geeta.rawat@example.com",
      gender: "Female",
      grade10: 93,
      grade12: 88,
      cgpa: 9.0,
      placedStatus: "Selected",
      placementType: "Off Campus",
      companyName: "Accenture",
      roleOffered: "Analyst",
      salary: 6.5,
      companiesPlaced: 1,
    },

    // ---------- 2022 Batch ----------
    {
      stdID: "2021FHIT001",
      name: "Pankaj Patel",
      passoutYear: "2022",
      contact: "9911122233",
      mailID: "pankaj.patel@example.com",
      gender: "Male",
      grade10: 81,
      grade12: 79,
      cgpa: 7.4,
      placedStatus: "Selected",
      placementType: "On Campus",
      companyName: "Wipro",
      roleOffered: "Associate Engineer",
      salary: 5,
      companiesPlaced: 1,
    },
    {
      stdID: "2021FHIT002",
      name: "Jyoti Chand",
      passoutYear: "2022",
      contact: "9922233344",
      mailID: "jyoti.chand@example.com",
      gender: "Female",
      grade10: 87,
      grade12: 84,
      cgpa: 8.3,
      placedStatus: "Rejected",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2021FHIT003",
      name: "Harish Nair",
      passoutYear: "2022",
      contact: "9933344455",
      mailID: "harish.nair@example.com",
      gender: "Male",
      grade10: 82,
      grade12: 80,
      cgpa: 7.8,
      placedStatus: "Applied",
      placementType: "Off Campus",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2021FHIT004",
      name: "Seema Gupta",
      passoutYear: "2022",
      contact: "9944455566",
      mailID: "seema.gupta@example.com",
      gender: "Female",
      grade10: 89,
      grade12: 88,
      cgpa: 8.5,
      placedStatus: "Selected",
      placementType: "On Campus",
      companyName: "Capgemini",
      roleOffered: "Software Engineer",
      salary: 6.5,
      companiesPlaced: 1,
    },
    {
      stdID: "2021FHIT005",
      name: "Amrit Mehra",
      passoutYear: "2022",
      contact: "9955566677",
      mailID: "amrit.mehra@example.com",
      gender: "Male",
      grade10: 75,
      grade12: 72,
      cgpa: 6.7,
      placedStatus: "Unregistered",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },

    // ---------- 2023 Batch ----------
    {
      stdID: "2022FHIT001",
      name: "Tanvi Iyer",
      passoutYear: "2023",
      contact: "9966677788",
      mailID: "tanvi.iyer@example.com",
      gender: "Female",
      grade10: 91,
      grade12: 90,
      cgpa: 9.0,
      placedStatus: "Applied",
      placementType: "On Campus",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2022FHIT002",
      name: "Nikhil Gaur",
      passoutYear: "2023",
      contact: "9977788899",
      mailID: "nikhil.gaur@example.com",
      gender: "Male",
      grade10: 83,
      grade12: 80,
      cgpa: 7.7,
      placedStatus: "Selected",
      placementType: "On Campus",
      companyName: "TCS",
      roleOffered: "Software Engineer",
      salary: 6,
      companiesPlaced: 1,
    },
    {
      stdID: "2022FHIT003",
      name: "Bhavana Deshpande",
      passoutYear: "2023",
      contact: "9988899900",
      mailID: "bhavana.d@example.com",
      gender: "Female",
      grade10: 88,
      grade12: 85,
      cgpa: 8.4,
      placedStatus: "Rejected",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2022FHIT004",
      name: "Ritesh Kohli",
      passoutYear: "2023",
      contact: "9999900011",
      mailID: "ritesh@example.com",
      gender: "Male",
      grade10: 80,
      grade12: 76,
      cgpa: 7.2,
      placedStatus: "Selected",
      placementType: "Off Campus",
      companyName: "Infosys",
      roleOffered: "System Engineer",
      salary: 5.5,
      companiesPlaced: 1,
    },
    {
      stdID: "2022FHIT005",
      name: "Neeraj Sharma",
      passoutYear: "2023",
      contact: "9123456800",
      mailID: "neeraj@example.com",
      gender: "Male",
      grade10: 78,
      grade12: 74,
      cgpa: 6.9,
      placedStatus: "Unregistered",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },

    // ---------- 2024 Batch (original, unchanged structure) ----------
    {
      stdID: "2023FHIT001",
      name: "Rahul Sharma",
      passoutYear: "2024",
      contact: "1234567890",
      mailID: "rahul@example.com",
      gender: "Male",
      grade10: 88,
      grade12: 85,
      cgpa: 8.2,
      placedStatus: "Selected",
      placementType: "On Campus",
      companyName: "TCS",
      roleOffered: "Software Engineer",
      salary: 6,
      companiesPlaced: 2,
    },
    {
      stdID: "2023FHIT002",
      name: "Neha Singh",
      passoutYear: "2024",
      contact: "9876543210",
      mailID: "neha@example.com",
      gender: "Female",
      grade10: 92,
      grade12: 90,
      cgpa: 9.1,
      placedStatus: "Rejected",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2023FHIT003",
      name: "Amit Verma",
      passoutYear: "2024",
      contact: "9990022110",
      mailID: "amitv@example.com",
      gender: "Male",
      grade10: 85,
      grade12: 78,
      cgpa: 7.5,
      placedStatus: "Selected",
      placementType: "Off Campus",
      companyName: "Infosys",
      roleOffered: "System Engineer",
      salary: 5.5,
      companiesPlaced: 1,
    },
    {
      stdID: "2023FHIT004",
      name: "Priya Nair",
      passoutYear: "2024",
      contact: "9345216789",
      mailID: "priya.nair@example.com",
      gender: "Female",
      grade10: 95,
      grade12: 91,
      cgpa: 9.4,
      placedStatus: "Selected",
      placementType: "On Campus",
      companyName: "Google",
      roleOffered: "Software Developer",
      salary: 45,
      companiesPlaced: 1,
    },

    // ---------- 2025 Batch (existing, kept with new statuses) ----------
    {
      stdID: "2024FHIT001",
      name: "Aditya Joshi",
      passoutYear: "2025",
      contact: "9112233445",
      mailID: "aditya@example.com",
      gender: "Male",
      grade10: 87,
      grade12: 81,
      cgpa: 8.1,
      placedStatus: "Selected",
      placementType: "On Campus",
      companyName: "IBM",
      roleOffered: "Associate Developer",
      salary: 8,
      companiesPlaced: 1,
    },
    {
      stdID: "2024FHIT002",
      name: "Divya Menon",
      passoutYear: "2025",
      contact: "9776655443",
      mailID: "divya@example.com",
      gender: "Female",
      grade10: 89,
      grade12: 85,
      cgpa: 8.5,
      placedStatus: "Selected",
      placementType: "On Campus",
      companyName: "Microsoft",
      roleOffered: "Software Engineer",
      salary: 38,
      companiesPlaced: 1,
    },
    {
      stdID: "2024FHIT003",
      name: "Vivek Rao",
      passoutYear: "2025",
      contact: "9887766550",
      mailID: "vivek@example.com",
      gender: "Male",
      grade10: 83,
      grade12: 78,
      cgpa: 7.4,
      placedStatus: "Rejected",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
    {
      stdID: "2024FHIT004",
      name: "Megha Kapoor",
      passoutYear: "2025",
      contact: "9556677889",
      mailID: "megha@example.com",
      gender: "Female",
      grade10: 90,
      grade12: 89,
      cgpa: 9.3,
      placedStatus: "Selected",
      placementType: "Off Campus",
      companyName: "Google",
      roleOffered: "Software Developer",
      salary: 45,
      companiesPlaced: 1,
    },
    {
      stdID: "2024FHIT005",
      name: "Ritesh Jain",
      passoutYear: "2025",
      contact: "9788812233",
      mailID: "ritesh@example.com",
      gender: "Male",
      grade10: 78,
      grade12: 74,
      cgpa: 6.8,
      placedStatus: "Unregistered",
      placementType: "N/A",
      companyName: "",
      roleOffered: "",
      salary: 0,
      companiesPlaced: 0,
    },
  ],

  companyData: [
    {
      name: "TCS",
      field: "IT Services",
      mail: "hr@tcs.com",
      role: "Software Engineer",
      eligibleStudents: 200,
      placedStudents: 55,
      location: "Mumbai",
      salary: "6 LPA",
      driveDate: "2025‑03‑15",
      rounds: 3,
      eligibility: { tenth: 60, twelfth: 60, cgpa: 6.0, ktsAllowed: 0 },
    },
    {
      name: "Infosys",
      field: "IT Services",
      mail: "jobs@infosys.com",
      role: "System Engineer",
      eligibleStudents: 180,
      placedStudents: 48,
      location: "Bangalore",
      salary: "5.5 LPA",
      driveDate: "2025‑02‑20",
      rounds: 2,
      eligibility: { tenth: 65, twelfth: 65, cgpa: 6.5, ktsAllowed: 1 },
    },
    {
      name: "Google",
      field: "Software",
      mail: "jobs@google.com",
      role: "Software Developer",
      eligibleStudents: 60,
      placedStudents: 12,
      location: "Hyderabad",
      salary: "45 LPA",
      driveDate: "2025‑01‑25",
      rounds: 5,
      eligibility: { tenth: 80, twelfth: 85, cgpa: 8.5, ktsAllowed: 0 },
    },
    {
      name: "Amazon",
      field: "E‑commerce",
      mail: "amazon‑hr@amazon.com",
      role: "SDE‑1",
      eligibleStudents: 100,
      placedStudents: 20,
      location: "Hyderabad",
      salary: "30 LPA",
      driveDate: "2025‑04‑10",
      rounds: 4,
      eligibility: { tenth: 70, twelfth: 70, cgpa: 7.0, ktsAllowed: 0 },
    },
    {
      name: "Accenture",
      field: "Consulting & IT Services",
      mail: "campus@accenture.com",
      role: "Software Analyst",
      eligibleStudents: 170,
      placedStudents: 52,
      location: "Pune",
      salary: "6.8 LPA",
      driveDate: "2025‑03‑05",
      rounds: 3,
      eligibility: { tenth: 60, twelfth: 60, cgpa: 6.0, ktsAllowed: 2 },
    },
    {
      name: "Microsoft",
      field: "Software",
      mail: "careers@microsoft.com",
      role: "Software Engineer",
      eligibleStudents: 40,
      placedStudents: 8,
      location: "Noida",
      salary: "38 LPA",
      driveDate: "2025‑01‑10",
      rounds: 4,
      eligibility: { tenth: 80, twelfth: 85, cgpa: 8.0, ktsAllowed: 0 },
    },
    {
      name: "Wipro",
      field: "IT Services",
      mail: "hr@wipro.com",
      role: "Associate Engineer",
      eligibleStudents: 150,
      placedStudents: 35,
      location: "Chennai",
      salary: "5 LPA",
      driveDate: "2025‑05‑05",
      rounds: 2,
      eligibility: { tenth: 55, twelfth: 55, cgpa: 5.5, ktsAllowed: 2 },
    },
    {
      name: "IBM",
      field: "IT Consulting",
      mail: "talent@ibm.com",
      role: "Developer Associate",
      eligibleStudents: 90,
      placedStudents: 18,
      location: "Gurgaon",
      salary: "8 LPA",
      driveDate: "2025‑02‑28",
      rounds: 3,
      eligibility: { tenth: 60, twelfth: 65, cgpa: 6.5, ktsAllowed: 1 },
    },
    {
      name: "Reliance Industries",
      field: "Energy & Manufacturing",
      mail: "hr@ril.com",
      role: "Graduate Trainee",
      eligibleStudents: 120,
      placedStudents: 25,
      location: "Mumbai",
      salary: "9 LPA",
      driveDate: "2024‑12‑10",
      rounds: 3,
      eligibility: { tenth: 70, twelfth: 70, cgpa: 7.0, ktsAllowed: 1 },
    },
    {
      name: "Capgemini",
      field: "IT Services",
      mail: "campus@capgemini.com",
      role: "Software Engineer",
      eligibleStudents: 160,
      placedStudents: 40,
      location: "Pune",
      salary: "7 LPA",
      driveDate: "2025‑02‑12",
      rounds: 3,
      eligibility: { tenth: 60, twelfth: 60, cgpa: 6.0, ktsAllowed: 1 },
    },
  ],

  yearwiseData: [
    {
      year: 2020,
      studentsPlaced: 120,
      companiesVisited: 25,
      avgSalary: "5 LPA",
      highestSalary: "15 LPA",
      lowestSalary: "3 LPA",
      placedPercentage: 75,
      totalRegistered: 160,
    },
    {
      year: 2021,
      studentsPlaced: 140,
      companiesVisited: 28,
      avgSalary: "6 LPA",
      highestSalary: "18 LPA",
      lowestSalary: "3.5 LPA",
      placedPercentage: 80,
      totalRegistered: 175,
    },
    {
      year: 2022,
      studentsPlaced: 155,
      companiesVisited: 30,
      avgSalary: "7 LPA",
      highestSalary: "22 LPA",
      lowestSalary: "4 LPA",
      placedPercentage: 82,
      totalRegistered: 190,
    },
    {
      year: 2023,
      studentsPlaced: 165,
      companiesVisited: 31,
      avgSalary: "8 LPA",
      highestSalary: "28 LPA",
      lowestSalary: "4.5 LPA",
      placedPercentage: 84,
      totalRegistered: 196,
    },
    {
      year: 2024,
      studentsPlaced: 180,
      companiesVisited: 35,
      avgSalary: "9 LPA",
      highestSalary: "45 LPA",
      lowestSalary: "5 LPA",
      placedPercentage: 88,
      totalRegistered: 205,
    },
    {
      year: 2025,
      studentsPlaced: 190,
      companiesVisited: 38,
      avgSalary: "9.6 LPA",
      highestSalary: "50 LPA",
      lowestSalary: "5.5 LPA",
      placedPercentage: 90,
      totalRegistered: 210,
    },
  ],
};

export default sampleData;
